name: Build

on:
  # push currently not needed and disabled
  push:
      #branches:
        #- v0.8.x # needs to be the same as vars.DEV_BRANCH

  pull_request:
    types: [closed]
    branches:
      - main
      - stable

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Get dll version
      id: dllversion
      shell: bash
      run: |
        version=$(grep -Eo 'const std::string pluginVersion = "[^"]+"' vSIDPlugin.h | cut -d'"' -f2)
        echo "Version is: $version"
        echo "version=$version" >> $GITHUB_OUTPUT
        
    - name: Determine prerelease of current build
      id: prerelease
      shell: bash
      run: |
        if [[ ${{github.ref}} != "refs/heads/stable" ]]; then
          echo "Prerelease is true"
          echo "prerelease=true" >> $GITHUB_OUTPUT
        else
          echo "Prerelease is not true"
          echo "prerelease=false" >> $GITHUB_OUTPUT
        fi
        echo "github.ref is ${{ github.ref }}"
        
    - name: Append commit sha to version
      if: ${{ steps.prerelease.outputs.prerelease == 'true' }}
      id: commitversion
      shell: bash
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        SHA_VERSION="${{steps.dllversion.outputs.version}}-custom-$SHORT_SHA"
        echo "shaversion=$SHA_VERSION" >> $GITHUB_OUTPUT
        echo "Versions. version = ${{steps.dllversion.outputs.version}}, short_sha = $SHORT_SHA, new_version = $SHA_VERSION"
        sed -i 's/const std::string pluginVersion = ".*";/const std::string pluginVersion = "'$SHA_VERSION'";/' vSIDPlugin.h      
      
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: 17

    - name: Download and unpack libcurl
      shell: pwsh
      run: |
        $curlVersion = "8.17.0"
        $curlTag = "curl-" + ($curlVersion -replace '\.', '_')
        $url = "https://github.com/curl/curl/archive/refs/tags/$curlTag.zip"

        Write-Host "Downloading libcurl $curlVersion from $url"

        New-Item -ItemType Directory -Force -Path external | Out-Null

        $zipPath = "external/curl.zip"
        Invoke-WebRequest -Uri $url -OutFile $zipPath

        # verify SHA256 for integrity
        # ps command: Get-FileHash .\filename.zip -Algorithm SHA256
        $expectedHash = "0BE15247C07422A0061FDA4758C0182BB9C688E40ECF968D1A0B92742A32667E"
        $hash = (Get-FileHash $zipPath -Algorithm SHA256).Hash.ToLower()
        if ($hash -ne $expectedHash.ToLower()) {
          Write-Error "Hash mismatch for libcurl archive. Expected $expectedHash but got $hash"
          exit 1
        }

        Expand-Archive -Path $zipPath -DestinationPath "external" -Force

        $repoName = "curl"
        
        $unpackedDir = Join-Path "external" "$repoName-$curlTag"   # → external/curl-curl-8_17_0
        
        if (Test-Path "external/curl") {
          Remove-Item -Recurse -Force "external/curl"
        }
        
        Rename-Item -Path $unpackedDir -NewName "curl"

    - name: Configure CMake
      # remove --trace for less verbosity
      run: cmake -B build -S . -A Win32 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl --trace
      
    - name: Build DLL
      # remove --verbose for less verbosity
      run: cmake --build build --config Release --verbose

    - name: Create PDB and MAP artifact
      uses: actions/upload-artifact@v7
      with:
        name: vSID-PDB_MAP
        path: |
          build\Release\*.pdb
          build\Release\*.map
          build\Release\*.dll
        if-no-files-found: error
        retention-days: 14